sudo: false
language: python
dist: focal
python:
  - "3.10"
branches:
  only:
    - master
install: pip install tox-travis
script: tox
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh semantic-release.sh; fi'
  - nvm install 16
  - sh prepare-vc-compliance-tests-config.sh
  - python3 setup.py install
  - npm ci
  - npm run test:vc-compliance
  - sh publish-vc-compliance-result.sh # if no changes, no commit